import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en' | 'ja' | 'ko' | 'es' | 'fr' | 'de' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  // 从 localStorage 获取保存的语言，或使用浏览器语言，默认中文
  const getInitialLanguage = (): Language => {
    const saved = localStorage.getItem('language');
    if (saved && ['zh', 'en', 'ja', 'ko', 'es', 'fr', 'de', 'ru'].includes(saved)) {
      return saved as Language;
    }
    
    // 检测浏览器语言
    const browserLang = navigator.language.toLowerCase();
    if (browserLang.startsWith('zh')) return 'zh';
    if (browserLang.startsWith('ja')) return 'ja';
    if (browserLang.startsWith('ko')) return 'ko';
    if (browserLang.startsWith('es')) return 'es';
    if (browserLang.startsWith('fr')) return 'fr';
    if (browserLang.startsWith('de')) return 'de';
    if (browserLang.startsWith('ru')) return 'ru';
    if (browserLang.startsWith('en')) return 'en';
    
    return 'zh'; // 默认中文
  };

  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  // 翻译函数
  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key; // 如果找不到翻译，返回键名
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// 翻译文本数据
const translations: Record<Language, any> = {
  zh: {
    nav: {
      markets: '行情',
      trading: '交易',
      stocks: '股票',
      forex: '外汇',
      assets: '资产',
      deposit: '充值',
      withdraw: '提现',
      login: '登录',
      register: '注册',
      logout: '退出',
      profile: '个人中心',
      language: '语言'
    },
    hero: {
      title: '全球领先的加密货币交易平台',
      subtitle: '安全、快速、专业的数字资产交易服务',
      startTrading: '开始交易',
      learnMore: '了解更多',
      trustUsers: '全球信任用户',
      dailyVolume: '24小时交易量',
      countries: '支持国家',
      coins: '上线币种'
    },
    features: {
      title: '为什么选择我们',
      security: '银行级安全',
      securityDesc: '冷热钱包分离，多重签名技术，资产安全无忧',
      speed: '极速交易',
      speedDesc: '撮合引擎处理速度达100万笔/秒',
      lowFee: '低手续费',
      lowFeeDesc: 'Maker 0.08%, Taker 0.1%，VIP 更优惠',
      global: '全球服务',
      globalDesc: '支持100+国家和地区，24/7客户服务'
    },
    market: {
      title: '热门交易对',
      pair: '交易对',
      price: '最新价',
      change: '24h涨跌',
      volume: '24h成交量',
      high: '24h最高',
      low: '24h最低',
      action: '交易'
    },
    marketTrends: {
      title: '市場趨勢',
      viewMore: '查看更多',
      categories: {
        forex: '外汇',
        stocks: '股票',
        crypto: '加密货币',
        futures: '期货',
        metals: '贵金属'
      },
      table: {
        pair: '交易對',
        price: '最新價',
        change: '24h漲跌幅',
        high: '24H 最高價',
        volume: '24H成交額',
        trend: '行情走勢'
      }
    },
    trading: {
      buy: '买入',
      sell: '卖出',
      limit: '限价',
      market: '市价',
      stop: '止损',
      amount: '数量',
      price: '价格',
      total: '总额',
      available: '可用',
      orderBook: '订单簿',
      recentTrades: '最近成交',
      myOrders: '我的订单',
      placeOrder: '下单',
      cancel: '取消',
      filled: '已成交',
      pending: '待成交',
      cancelled: '已取消'
    },
    assets: {
      title: '我的资产',
      totalAssets: '总资产',
      available: '可用余额',
      frozen: '冻结资产',
      coin: '币种',
      balance: '余额',
      value: '估值',
      deposit: '充值',
      withdraw: '提现',
      transfer: '划转',
      history: '历史记录'
    },
    auth: {
      login: '登录',
      register: '注册',
      email: '邮箱',
      password: '密码',
      confirmPassword: '确认密码',
      forgotPassword: '忘记密码？',
      noAccount: '还没有账户？',
      hasAccount: '已有账户？',
      loginNow: '立即登录',
      registerNow: '立即注册',
      googleLogin: '使用 Google 登录',
      signInWithGoogle: '使用 Google 登录',
      createAccount: '创建账户',
      startTrading: '开始您的交易之旅',
      signInSubtitle: '使用邮箱登录继续',
      signUpSubtitle: '注册账户开始使用',
      welcome: '欢迎',
      welcomeBack: '欢迎回来',
      accessAccount: '访问您的账户并继续您的旅程',
      emailAddress: '邮箱地址',
      keepMeSignedIn: '保持登录状态',
      resetPassword: '重置密码',
      signIn: '登录',
      signInLoading: '登录中...',
      signUp: '注册',
      signUpLoading: '注册中...',
      createAccountLoading: '创建账户中...',
      orContinueWith: '或使用以下方式继续',
      newToPlatform: '新用户？',
      alreadyHaveAccount: '已有账户？',
      enterEmail: '输入您的邮箱',
      enterPhone: '请输入手机号码（可选）',
      enterPassword: '输入您的密码',
      enterEmailPlaceholder: '输入您的邮箱地址',
      enterPasswordPlaceholder: '输入您的密码',
      createPasswordPlaceholder: '创建密码（至少6个字符）',
      confirmPasswordPlaceholder: '确认您的密码',
      passwordsDoNotMatch: '密码不匹配',
      enterCode: '输入验证码',
      or: '或',
      sendCode: '发送验证码',
      verify: '验证',
      success: '成功！',
      loginSuccess: '登录成功',
      registerSuccess: '注册成功',
      agreeTerms: '我已阅读并同意服务条款和隐私政策',
      termsAndPrivacy: '注册即表示您同意',
      terms: '服务条款',
      and: '以及',
      privacy: '隐私政策',
      sending: '发送中...',
      codeSentTitle: '请查收邮箱',
      codeSentSubtitle: '我们已发送验证码',
      resendCode: '重新发送验证码',
      back: '返回',
      continue: '继续',
      continueToDashboard: '进入控制台',
      termsNoticeLogin: '登录即表示您同意',
      msa: 'MSA',
      productTerms: '产品条款',
      policies: '政策',
      privacyNotice: '隐私声明',
      cookieNotice: 'Cookie 声明'
    },
    footer: {
      about: '关于我们',
      terms: '服务条款',
      privacy: '隐私政策',
      support: '帮助中心',
      api: 'API文档',
      fees: '费率说明',
      announcement: '公告中心',
      careers: '加入我们',
      copyright: '© 2024 CRYPTONX. 保留所有权利。'
    },
    homepage: {
      cta: {
        title: '准备好开启您的\n财富之旅了吗？',
        description: '加入我们，轻松掌控您的财富收益',
        button: '开启交易'
      }
    },
    common: {
      search: '搜索',
      filter: '筛选',
      all: '全部',
      confirm: '确认',
      cancel: '取消',
      submit: '提交',
      save: '保存',
      delete: '删除',
      edit: '编辑',
      view: '查看',
      download: '下载',
      upload: '上传',
      loading: '加载中...',
      noData: '暂无数据',
      error: '错误',
      success: '成功',
      warning: '警告',
      info: '信息',
      more: '更多',
      less: '收起',
      expand: '展开',
      collapse: '折叠'
    }
  },
  en: {
    nav: {
      markets: 'Markets',
      trading: 'Trading',
      stocks: 'Stocks',
      forex: 'Forex',
      assets: 'Assets',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      login: 'Login',
      register: 'Sign Up',
      logout: 'Logout',
      profile: 'Profile',
      language: 'Language'
    },
    hero: {
      title: 'Leading Global Cryptocurrency Exchange',
      subtitle: 'Safe, Fast, and Professional Digital Asset Trading',
      startTrading: 'Start Trading',
      learnMore: 'Learn More',
      trustUsers: 'Trusted Users',
      dailyVolume: '24h Volume',
      countries: 'Countries',
      coins: 'Listed Coins'
    },
    features: {
      title: 'Why Choose Us',
      security: 'Bank-Level Security',
      securityDesc: 'Cold/hot wallet separation, multi-signature technology',
      speed: 'Lightning Fast',
      speedDesc: 'Matching engine handles 1M trades/sec',
      lowFee: 'Low Fees',
      lowFeeDesc: 'Maker 0.08%, Taker 0.1%, VIP even better',
      global: 'Global Service',
      globalDesc: '100+ countries, 24/7 customer support'
    },
    market: {
      title: 'Popular Trading Pairs',
      pair: 'Pair',
      price: 'Last Price',
      change: '24h Change',
      volume: '24h Volume',
      high: '24h High',
      low: '24h Low',
      action: 'Trade'
    },
    marketTrends: {
      title: 'Market Trends',
      viewMore: 'View More',
      categories: {
        forex: 'Forex',
        stocks: 'Stocks',
        crypto: 'Crypto',
        futures: 'Futures',
        metals: 'Precious Metals'
      },
      table: {
        pair: 'Pair',
        price: 'Last Price',
        change: '24h Change',
        high: '24h High',
        volume: '24h Volume',
        trend: 'Trend'
      }
    },
    trading: {
      buy: 'Buy',
      sell: 'Sell',
      limit: 'Limit',
      market: 'Market',
      stop: 'Stop',
      amount: 'Amount',
      price: 'Price',
      total: 'Total',
      available: 'Available',
      orderBook: 'Order Book',
      recentTrades: 'Recent Trades',
      myOrders: 'My Orders',
      placeOrder: 'Place Order',
      cancel: 'Cancel',
      filled: 'Filled',
      pending: 'Pending',
      cancelled: 'Cancelled'
    },
    assets: {
      title: 'My Assets',
      totalAssets: 'Total Assets',
      available: 'Available',
      frozen: 'Frozen',
      coin: 'Coin',
      balance: 'Balance',
      value: 'Value',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      transfer: 'Transfer',
      history: 'History'
    },
    auth: {
      login: 'Login',
      register: 'Sign Up',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      forgotPassword: 'Forgot Password?',
      noAccount: "Don't have an account?",
      hasAccount: 'Already have an account?',
      loginNow: 'Login Now',
      registerNow: 'Sign Up Now',
      googleLogin: 'Sign in with Google',
      signInWithGoogle: 'Sign in with Google',
      createAccount: 'Create Account',
      startTrading: 'Start your trading journey',
      signInSubtitle: 'Sign in with your email to continue',
      signUpSubtitle: 'Sign up to get started',
      welcome: 'Welcome',
      welcomeBack: 'Welcome Back',
      accessAccount: 'Access your account and continue your journey with us',
      emailAddress: 'Email Address',
      keepMeSignedIn: 'Keep me signed in',
      resetPassword: 'Reset password',
      signIn: 'Sign In',
      signInLoading: 'Signing in...',
      signUp: 'Sign Up',
      signUpLoading: 'Signing up...',
      createAccountLoading: 'Creating account...',
      orContinueWith: 'Or continue with',
      newToPlatform: 'New to our platform?',
      alreadyHaveAccount: 'Already have an account?',
      enterEmail: 'Enter your email',
      enterPhone: 'Enter your phone number (optional)',
      enterPassword: 'Enter your password',
      enterEmailPlaceholder: 'Enter your email address',
      enterPasswordPlaceholder: 'Enter your password',
      createPasswordPlaceholder: 'Create a password (min 6 characters)',
      confirmPasswordPlaceholder: 'Confirm your password',
      passwordsDoNotMatch: 'Passwords do not match',
      enterCode: 'Enter verification code',
      or: 'or',
      sendCode: 'Send Code',
      verify: 'Verify',
      success: 'Success!',
      loginSuccess: 'Login successful',
      registerSuccess: 'Registration successful',
      agreeTerms: 'I agree to the Terms of Service and Privacy Policy',
      termsAndPrivacy: 'By continuing, you agree to our',
      terms: 'Terms of Service',
      and: 'and',
      privacy: 'Privacy Policy',
      sending: 'Sending...',
      codeSentTitle: 'Check your inbox',
      codeSentSubtitle: "We've sent you a passcode",
      resendCode: 'Resend code',
      back: 'Back',
      continue: 'Continue',
      continueToDashboard: 'Continue to Dashboard',
      termsNoticeLogin: 'By signing in, you agree to the',
      msa: 'MSA',
      productTerms: 'Product Terms',
      policies: 'Policies',
      privacyNotice: 'Privacy Notice',
      cookieNotice: 'Cookie Notice'
    },
    footer: {
      about: 'About Us',
      terms: 'Terms of Service',
      privacy: 'Privacy Policy',
      support: 'Support',
      api: 'API Docs',
      fees: 'Fee Schedule',
      announcement: 'Announcements',
      careers: 'Careers',
      copyright: '© 2024 CRYPTONX. All rights reserved.'
    },
    homepage: {
      cta: {
        title: 'Ready to start your\nwealth journey?',
        description: 'Join us and take control of your wealth gains',
        button: 'Start Trading'
      }
    },
    common: {
      search: 'Search',
      filter: 'Filter',
      all: 'All',
      confirm: 'Confirm',
      cancel: 'Cancel',
      submit: 'Submit',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      download: 'Download',
      upload: 'Upload',
      loading: 'Loading...',
      noData: 'No Data',
      error: 'Error',
      success: 'Success',
      warning: 'Warning',
      info: 'Info',
      more: 'More',
      less: 'Less',
      expand: 'Expand',
      collapse: 'Collapse'
    }
  },
  ja: {
    nav: {
      markets: '市場',
      trading: '取引',
      stocks: '株式',
      forex: '外国為替',
      assets: '資産',
      deposit: '入金',
      withdraw: '出金',
      login: 'ログイン',
      register: '登録',
      logout: 'ログアウト',
      profile: 'プロフィール',
      language: '言語'
    },
    hero: {
      title: '世界をリードする仮想通貨取引所',
      subtitle: '安全、高速、プロフェッショナルなデジタル資産取引',
      startTrading: '取引開始',
      learnMore: '詳細を見る',
      trustUsers: '信頼するユーザー',
      dailyVolume: '24時間取引高',
      countries: '対応国',
      coins: '上場通貨'
    },
    features: {
      title: '選ばれる理由',
      security: '銀行レベルのセキュリティ',
      securityDesc: 'コールド/ホットウォレット分離、マルチシグ技術',
      speed: '超高速取引',
      speedDesc: 'マッチングエンジンは毎秒100万件処理',
      lowFee: '低手数料',
      lowFeeDesc: 'Maker 0.08%, Taker 0.1%, VIPさらにお得',
      global: 'グローバルサービス',
      globalDesc: '100以上の国、24/7カスタマーサポート'
    },
    market: {
      title: '人気の取引ペア',
      pair: 'ペア',
      price: '最新価格',
      change: '24h変動',
      volume: '24h出来高',
      high: '24h高値',
      low: '24h安値',
      action: '取引'
    },
    marketTrends: {
      title: '市場趨勢',
      viewMore: 'もっと見る',
      categories: {
        forex: '外汇',
        stocks: '股票',
        crypto: '暗号通貨',
        futures: '先物',
        metals: '貴金属'
      },
      table: {
        pair: 'ペア',
        price: '最新価格',
        change: '24h変動率',
        high: '24h高値',
        volume: '24h出来高',
        trend: 'トレンド'
      }
    },
    trading: {
      buy: '買い',
      sell: '売り',
      limit: '指値',
      market: '成行',
      stop: 'ストップ',
      amount: '数量',
      price: '価格',
      total: '合計',
      available: '利用可能',
      orderBook: '注文板',
      recentTrades: '最近の取引',
      myOrders: 'マイオーダー',
      placeOrder: '注文',
      cancel: 'キャンセル',
      filled: '約定済み',
      pending: '待機中',
      cancelled: 'キャンセル済み'
    },
    assets: {
      title: 'マイアセット',
      totalAssets: '総資産',
      available: '利用可能',
      frozen: '凍結',
      coin: '通貨',
      balance: '残高',
      value: '評価額',
      deposit: '入金',
      withdraw: '出金',
      transfer: '振替',
      history: '履歴'
    },
    auth: {
      login: 'ログイン',
      register: '登録',
      email: 'メール',
      password: 'パスワード',
      confirmPassword: 'パスワード確認',
      forgotPassword: 'パスワードをお忘れですか？',
      noAccount: 'アカウントをお持ちでないですか？',
      hasAccount: 'すでにアカウントをお持ちですか？',
      loginNow: '今すぐログイン',
      registerNow: '今すぐ登録',
      googleLogin: 'Googleでログイン',
      signInWithGoogle: 'Googleでログイン',
      createAccount: 'アカウント作成',
      startTrading: '取引を開始しましょう',
      signInSubtitle: 'メールアドレスでログインして続行',
      signUpSubtitle: '登録して始める',
      welcome: 'ようこそ',
      welcomeBack: 'お帰りなさい',
      accessAccount: 'アカウントにアクセスして、旅を続けましょう',
      emailAddress: 'メールアドレス',
      keepMeSignedIn: 'ログイン状態を保持',
      resetPassword: 'パスワードをリセット',
      signIn: 'ログイン',
      signInLoading: 'ログイン中...',
      signUp: '登録',
      signUpLoading: '登録中...',
      createAccountLoading: 'アカウント作成中...',
      orContinueWith: 'または以下で続行',
      newToPlatform: '初めての方ですか？',
      alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
      enterEmail: 'メールアドレスを入力',
      enterPhone: '電話番号を入力（任意）',
      enterPassword: 'パスワードを入力',
      enterEmailPlaceholder: 'メールアドレスを入力してください',
      enterPasswordPlaceholder: 'パスワードを入力してください',
      createPasswordPlaceholder: 'パスワードを作成（最低6文字）',
      confirmPasswordPlaceholder: 'パスワードを確認',
      passwordsDoNotMatch: 'パスワードが一致しません',
      enterCode: '確認コードを入力',
      or: 'または',
      sendCode: 'コード送信',
      verify: '確認',
      success: '成功！',
      loginSuccess: 'ログイン成功',
      registerSuccess: '登録成功',
      agreeTerms: '利用規約とプライバシーポリシーに同意します',
      termsAndPrivacy: '続行すると、以下に同意したとみなされます',
      terms: '利用規約',
      and: 'および',
      privacy: 'プライバシーポリシー',
      sending: '送信中...',
      codeSentTitle: 'メールボックスを確認してください',
      codeSentSubtitle: '確認コードを送信しました',
      resendCode: 'コードを再送信',
      back: '戻る',
      continue: '続行',
      continueToDashboard: 'ダッシュボードへ',
      termsNoticeLogin: 'ログインすると、次に同意したものとみなされます',
      msa: 'MSA',
      productTerms: '製品利用規約',
      policies: 'ポリシー',
      privacyNotice: 'プライバシー通知',
      cookieNotice: 'Cookie 通知'
    },
    footer: {
      about: '会社概要',
      terms: '利用規約',
      privacy: 'プライバシーポリシー',
      support: 'サポート',
      api: 'APIドキュメント',
      fees: '手数料',
      announcement: 'お知らせ',
      careers: '採用情報',
      copyright: '© 2024 CRYPTONX. 全著作権所有。'
    },
    homepage: {
      cta: {
        title: '財産の旅を\n始めますか？',
        description: '私たちに参加し、財産の利益をコントロールしましょう',
        button: '取引を開始'
      }
    },
    common: {
      search: '検索',
      filter: 'フィルター',
      all: 'すべて',
      confirm: '確認',
      cancel: 'キャンセル',
      submit: '送信',
      save: '保存',
      delete: '削除',
      edit: '編集',
      view: '表示',
      download: 'ダウンロード',
      upload: 'アップロード',
      loading: '読み込み中...',
      noData: 'データなし',
      error: 'エラー',
      success: '成功',
      warning: '警告',
      info: '情報',
      more: 'もっと見る',
      less: '閉じる',
      expand: '展開',
      collapse: '折りたたむ'
    }
  },
  ko: {
    nav: {
      markets: '시장',
      trading: '거래',
      stocks: '주식',
      forex: '외환',
      assets: '자산',
      deposit: '입금',
      withdraw: '출금',
      login: '로그인',
      register: '가입',
      logout: '로그아웃',
      profile: '프로필',
      language: '언어'
    },
    hero: {
      title: '세계 최고의 암호화폐 거래소',
      subtitle: '안전하고 빠른 전문 디지털 자산 거래',
      startTrading: '거래 시작',
      learnMore: '자세히 보기',
      trustUsers: '신뢰하는 사용자',
      dailyVolume: '24시간 거래량',
      countries: '지원 국가',
      coins: '상장 코인'
    },
    features: {
      title: '선택하는 이유',
      security: '은행급 보안',
      securityDesc: '콜드/핫 지갑 분리, 다중 서명 기술',
      speed: '초고속 거래',
      speedDesc: '매칭 엔진 초당 100만 건 처리',
      lowFee: '낮은 수수료',
      lowFeeDesc: 'Maker 0.08%, Taker 0.1%, VIP 더 저렴',
      global: '글로벌 서비스',
      globalDesc: '100개 이상 국가, 24/7 고객 지원'
    },
    market: {
      title: '인기 거래쌍',
      pair: '거래쌍',
      price: '최근 가격',
      change: '24시간 변동',
      volume: '24시간 거래량',
      high: '24시간 최고',
      low: '24시간 최저',
      action: '거래'
    },
    marketTrends: {
      title: '시장 트렌드',
      viewMore: '더 보기',
      categories: {
        forex: '외환',
        stocks: '주식',
        crypto: '암호화폐',
        futures: '선물',
        metals: '금속'
      },
      table: {
        pair: '거래 쌍',
        price: '최근 가격',
        change: '24시간 변동률',
        high: '24시간 최고가',
        volume: '24시간 거래량',
        trend: '트렌드'
      }
    },
    trading: {
      buy: '매수',
      sell: '매도',
      limit: '지정가',
      market: '시장가',
      stop: '손절',
      amount: '수량',
      price: '가격',
      total: '총액',
      available: '사용 가능',
      orderBook: '주문장',
      recentTrades: '최근 거래',
      myOrders: '내 주문',
      placeOrder: '주문하기',
      cancel: '취소',
      filled: '체결',
      pending: '대기 중',
      cancelled: '취소됨'
    },
    assets: {
      title: '내 자산',
      totalAssets: '총 자산',
      available: '사용 가능',
      frozen: '동결',
      coin: '코인',
      balance: '잔액',
      value: '가치',
      deposit: '입금',
      withdraw: '출금',
      transfer: '이체',
      history: '내역'
    },
    auth: {
      login: '로그인',
      register: '가입',
      email: '이메일',
      password: '비밀번호',
      confirmPassword: '비밀번호 확인',
      forgotPassword: '비밀번호를 잊으셨나요?',
      noAccount: '계정이 없으신가요?',
      hasAccount: '이미 계정이 있으신가요?',
      loginNow: '지금 로그인',
      registerNow: '지금 가입',
      googleLogin: 'Google로 로그인',
      signInWithGoogle: 'Google로 로그인',
      createAccount: '계정 만들기',
      startTrading: '거래 여정을 시작하세요',
      signInSubtitle: '이메일로 로그인하여 계속하세요',
      signUpSubtitle: '가입하여 시작하세요',
      welcome: '환영합니다',
      welcomeBack: '다시 오신 것을 환영합니다',
      accessAccount: '계정에 액세스하여 여정을 계속하세요',
      emailAddress: '이메일 주소',
      keepMeSignedIn: '로그인 상태 유지',
      resetPassword: '비밀번호 재설정',
      signIn: '로그인',
      signInLoading: '로그인 중...',
      signUp: '가입',
      signUpLoading: '가입 중...',
      createAccountLoading: '계정 생성 중...',
      orContinueWith: '또는 다음으로 계속',
      newToPlatform: '처음이신가요?',
      alreadyHaveAccount: '이미 계정이 있으신가요?',
      enterEmail: '이메일을 입력하세요',
      enterPhone: '전화번호를 입력하세요 (선택 사항)',
      enterPassword: '비밀번호를 입력하세요',
      enterEmailPlaceholder: '이메일 주소를 입력하세요',
      enterPasswordPlaceholder: '비밀번호를 입력하세요',
      createPasswordPlaceholder: '비밀번호 생성 (최소 6자)',
      confirmPasswordPlaceholder: '비밀번호 확인',
      passwordsDoNotMatch: '비밀번호가 일치하지 않습니다',
      enterCode: '인증 코드 입력',
      or: '또는',
      sendCode: '코드 전송',
      verify: '확인',
      success: '성공!',
      loginSuccess: '로그인 성공',
      registerSuccess: '가입 성공',
      agreeTerms: '서비스 약관 및 개인정보 보호정책에 동의합니다',
      termsAndPrivacy: '계속하면 다음에 동의하게 됩니다',
      terms: '서비스 약관',
      and: '및',
      privacy: '개인정보 보호정책',
      sending: '전송 중...',
      codeSentTitle: '메일함을 확인하세요',
      codeSentSubtitle: '인증 코드를 보냈습니다',
      resendCode: '코드 다시 보내기',
      back: '뒤로',
      continue: '계속',
      continueToDashboard: '대시보드로 이동',
      termsNoticeLogin: '로그인하면 다음에 동의하게 됩니다',
      msa: 'MSA',
      productTerms: '제품 약관',
      policies: '정책',
      privacyNotice: '개인정보 보호 고지',
      cookieNotice: '쿠키 고지'
    },
    footer: {
      about: '회사 소개',
      terms: '서비스 약관',
      privacy: '개인정보 보호정책',
      support: '고객 지원',
      api: 'API 문서',
      fees: '수수료 안내',
      announcement: '공지사항',
      careers: '채용',
      copyright: '© 2024 CRYPTONX. 모든 권리 보유.'
    },
    homepage: {
      cta: {
        title: '재산 여행을\n시작할 준비가 되셨나요?',
        description: '우리와 함께 재산 수익을 관리하세요',
        button: '거래 시작'
      }
    },
    common: {
      search: '검색',
      filter: '필터',
      all: '전체',
      confirm: '확인',
      cancel: '취소',
      submit: '제출',
      save: '저장',
      delete: '삭제',
      edit: '편집',
      view: '보기',
      download: '다운로드',
      upload: '업로드',
      loading: '로딩 중...',
      noData: '데이터 없음',
      error: '오류',
      success: '성공',
      warning: '경고',
      info: '정보',
      more: '더 보기',
      less: '접기',
      expand: '펼치기',
      collapse: '접기'
    }
  },
  es: {
    nav: {
      markets: 'Mercados',
      trading: 'Trading',
      stocks: 'Acciones',
      forex: 'Forex',
      assets: 'Activos',
      deposit: 'Depósito',
      withdraw: 'Retiro',
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      logout: 'Cerrar Sesión',
      profile: 'Perfil',
      language: 'Idioma'
    },
    hero: {
      title: 'Exchange de Criptomonedas Líder Mundial',
      subtitle: 'Trading Seguro, Rápido y Profesional de Activos Digitales',
      startTrading: 'Comenzar a Operar',
      learnMore: 'Más Información',
      trustUsers: 'Usuarios de Confianza',
      dailyVolume: 'Volumen 24h',
      countries: 'Países',
      coins: 'Monedas Listadas'
    },
    features: {
      title: 'Por Qué Elegirnos',
      security: 'Seguridad Bancaria',
      securityDesc: 'Separación de billeteras frías/calientes, tecnología multi-firma',
      speed: 'Ultra Rápido',
      speedDesc: 'Motor de emparejamiento maneja 1M operaciones/seg',
      lowFee: 'Tarifas Bajas',
      lowFeeDesc: 'Maker 0.08%, Taker 0.1%, VIP aún mejor',
      global: 'Servicio Global',
      globalDesc: '100+ países, soporte 24/7'
    },
    market: {
      title: 'Pares Populares',
      pair: 'Par',
      price: 'Último Precio',
      change: 'Cambio 24h',
      volume: 'Volumen 24h',
      high: 'Máximo 24h',
      low: 'Mínimo 24h',
      action: 'Operar'
    },
    marketTrends: {
      title: 'Tendencias del Mercado',
      viewMore: 'Ver más',
      categories: {
        forex: 'Forex',
        stocks: 'Acciones',
        crypto: 'Criptomonedas',
        futures: 'Futuros',
        metals: 'Metales Preciosos'
      },
      table: {
        pair: 'Par',
        price: 'Último Precio',
        change: 'Cambio 24h',
        high: 'Máximo 24h',
        volume: 'Volumen 24h',
        trend: 'Tendencia'
      }
    },
    trading: {
      buy: 'Comprar',
      sell: 'Vender',
      limit: 'Límite',
      market: 'Mercado',
      stop: 'Stop',
      amount: 'Cantidad',
      price: 'Precio',
      total: 'Total',
      available: 'Disponible',
      orderBook: 'Libro de Órdenes',
      recentTrades: 'Operaciones Recientes',
      myOrders: 'Mis Órdenes',
      placeOrder: 'Colocar Orden',
      cancel: 'Cancelar',
      filled: 'Completado',
      pending: 'Pendiente',
      cancelled: 'Cancelado'
    },
    assets: {
      title: 'Mis Activos',
      totalAssets: 'Activos Totales',
      available: 'Disponible',
      frozen: 'Congelado',
      coin: 'Moneda',
      balance: 'Balance',
      value: 'Valor',
      deposit: 'Depósito',
      withdraw: 'Retiro',
      transfer: 'Transferir',
      history: 'Historial'
    },
    auth: {
      login: 'Iniciar Sesión',
      register: 'Registrarse',
      email: 'Correo',
      password: 'Contraseña',
      confirmPassword: 'Confirmar Contraseña',
      forgotPassword: '¿Olvidaste tu contraseña?',
      noAccount: '¿No tienes cuenta?',
      hasAccount: '¿Ya tienes cuenta?',
      loginNow: 'Iniciar Sesión',
      registerNow: 'Registrarse',
      googleLogin: 'Iniciar con Google',
      signInWithGoogle: 'Iniciar con Google',
      createAccount: 'Crear Cuenta',
      startTrading: 'Comienza tu viaje de trading',
      signInSubtitle: 'Inicia sesión con tu correo para continuar',
      signUpSubtitle: 'Regístrate para comenzar',
      welcome: 'Bienvenido',
      welcomeBack: 'Bienvenido de nuevo',
      accessAccount: 'Accede a tu cuenta y continúa tu viaje con nosotros',
      emailAddress: 'Correo Electrónico',
      keepMeSignedIn: 'Mantenerme conectado',
      resetPassword: 'Restablecer contraseña',
      signIn: 'Iniciar Sesión',
      signInLoading: 'Iniciando sesión...',
      signUp: 'Registrarse',
      signUpLoading: 'Registrando...',
      createAccountLoading: 'Creando cuenta...',
      orContinueWith: 'O continúa con',
      newToPlatform: '¿Eres nuevo en nuestra plataforma?',
      alreadyHaveAccount: '¿Ya tienes una cuenta?',
      enterEmail: 'Ingresa tu correo',
      enterPhone: 'Ingresa tu número de teléfono (opcional)',
      enterPassword: 'Ingresa tu contraseña',
      enterEmailPlaceholder: 'Ingresa tu correo electrónico',
      enterPasswordPlaceholder: 'Ingresa tu contraseña',
      createPasswordPlaceholder: 'Crea una contraseña (mín. 6 caracteres)',
      confirmPasswordPlaceholder: 'Confirma tu contraseña',
      passwordsDoNotMatch: 'Las contraseñas no coinciden',
      enterCode: 'Ingresa código de verificación',
      or: 'o',
      sendCode: 'Enviar Código',
      verify: 'Verificar',
      success: '¡Éxito!',
      loginSuccess: 'Inicio de sesión exitoso',
      registerSuccess: 'Registro exitoso',
      agreeTerms: 'Acepto los Términos de servicio y la Política de privacidad',
      termsAndPrivacy: 'Al continuar aceptas nuestros',
      terms: 'Términos de servicio',
      and: 'y',
      privacy: 'Política de privacidad',
      sending: 'Enviando...'
    },
    footer: {
      about: 'Acerca de',
      terms: 'Términos de Servicio',
      privacy: 'Política de Privacidad',
      support: 'Soporte',
      api: 'Documentación API',
      fees: 'Tarifas',
      announcement: 'Anuncios',
      careers: 'Empleos',
      copyright: '© 2024 CRYPTONX. Todos los derechos reservados.'
    },
    homepage: {
      cta: {
        title: '¿Estás listo para comenzar tu\nviaje de riqueza?',
        description: 'Únete a nosotros y toma el control de tus ganancias',
        button: 'Comenzar a operar'
      }
    },
    common: {
      search: 'Buscar',
      filter: 'Filtrar',
      all: 'Todo',
      confirm: 'Confirmar',
      cancel: 'Cancelar',
      submit: 'Enviar',
      save: 'Guardar',
      delete: 'Eliminar',
      edit: 'Editar',
      view: 'Ver',
      download: 'Descargar',
      upload: 'Subir',
      loading: 'Cargando...',
      noData: 'Sin Datos',
      error: 'Error',
      success: 'Éxito',
      warning: 'Advertencia',
      info: 'Info',
      more: 'Más',
      less: 'Menos',
      expand: 'Expandir',
      collapse: 'Colapsar'
    }
  },
  fr: {
    nav: {
      markets: 'Marchés',
      trading: 'Trading',
      stocks: 'Actions',
      forex: 'Forex',
      assets: 'Actifs',
      deposit: 'Dépôt',
      withdraw: 'Retrait',
      login: 'Connexion',
      register: "S'inscrire",
      logout: 'Déconnexion',
      profile: 'Profil',
      language: 'Langue'
    },
    hero: {
      title: 'Exchange de Cryptomonnaies Leader Mondial',
      subtitle: 'Trading Sécurisé, Rapide et Professionnel',
      startTrading: 'Commencer',
      learnMore: 'En Savoir Plus',
      trustUsers: 'Utilisateurs',
      dailyVolume: 'Volume 24h',
      countries: 'Pays',
      coins: 'Cryptos Listées'
    },
    features: {
      title: 'Pourquoi Nous Choisir',
      security: 'Sécurité Bancaire',
      securityDesc: 'Séparation portefeuilles chauds/froids, multi-signature',
      speed: 'Ultra Rapide',
      speedDesc: 'Moteur traite 1M transactions/sec',
      lowFee: 'Frais Bas',
      lowFeeDesc: 'Maker 0.08%, Taker 0.1%, VIP encore mieux',
      global: 'Service Global',
      globalDesc: '100+ pays, support 24/7'
    },
    market: {
      title: 'Paires Populaires',
      pair: 'Paire',
      price: 'Dernier Prix',
      change: 'Variation 24h',
      volume: 'Volume 24h',
      high: 'Haut 24h',
      low: 'Bas 24h',
      action: 'Trader'
    },
    marketTrends: {
      title: 'Tendances du Marché',
      viewMore: 'Voir plus',
      categories: {
        forex: 'Forex',
        stocks: 'Actions',
        crypto: 'Cryptomonnaies',
        futures: 'Futurs',
        metals: 'Métaux Précieux'
      },
      table: {
        pair: 'Paire',
        price: 'Dernier Prix',
        change: 'Variation 24h',
        high: 'Haut 24h',
        volume: 'Volume 24h',
        trend: 'Tendance'
      }
    },
    trading: {
      buy: 'Acheter',
      sell: 'Vendre',
      limit: 'Limite',
      market: 'Marché',
      stop: 'Stop',
      amount: 'Montant',
      price: 'Prix',
      total: 'Total',
      available: 'Disponible',
      orderBook: 'Carnet',
      recentTrades: 'Trades Récents',
      myOrders: 'Mes Ordres',
      placeOrder: 'Placer Ordre',
      cancel: 'Annuler',
      filled: 'Rempli',
      pending: 'En Attente',
      cancelled: 'Annulé'
    },
    assets: {
      title: 'Mes Actifs',
      totalAssets: 'Actifs Totaux',
      available: 'Disponible',
      frozen: 'Gelé',
      coin: 'Crypto',
      balance: 'Solde',
      value: 'Valeur',
      deposit: 'Dépôt',
      withdraw: 'Retrait',
      transfer: 'Transférer',
      history: 'Historique'
    },
    auth: {
      login: 'Connexion',
      register: "S'inscrire",
      email: 'Email',
      password: 'Mot de Passe',
      confirmPassword: 'Confirmer Mot de Passe',
      forgotPassword: 'Mot de passe oublié?',
      noAccount: 'Pas de compte?',
      hasAccount: 'Déjà un compte?',
      loginNow: 'Se Connecter',
      registerNow: "S'inscrire",
      googleLogin: 'Connexion Google',
      signInWithGoogle: 'Connexion Google',
      createAccount: 'Créer un Compte',
      startTrading: 'Commencez votre voyage de trading',
      signInSubtitle: "Connectez-vous avec votre e-mail pour continuer",
      signUpSubtitle: 'Inscrivez-vous pour commencer',
      welcome: 'Bienvenue',
      welcomeBack: 'Bon retour',
      accessAccount: 'Accédez à votre compte et poursuivez votre voyage avec nous',
      emailAddress: 'Adresse E-mail',
      keepMeSignedIn: 'Rester connecté',
      resetPassword: 'Réinitialiser le mot de passe',
      signIn: 'Se Connecter',
      signInLoading: 'Connexion en cours...',
      signUp: "S'inscrire",
      signUpLoading: 'Inscription en cours...',
      createAccountLoading: 'Création du compte...',
      orContinueWith: 'Ou continuer avec',
      newToPlatform: 'Nouveau sur notre plateforme ?',
      alreadyHaveAccount: 'Vous avez déjà un compte ?',
      enterEmail: 'Entrez votre e-mail',
      enterPhone: 'Entrez votre numéro de téléphone (optionnel)',
      enterPassword: 'Entrez votre mot de passe',
      enterEmailPlaceholder: 'Entrez votre adresse e-mail',
      enterPasswordPlaceholder: 'Entrez votre mot de passe',
      createPasswordPlaceholder: 'Créez un mot de passe (min. 6 caractères)',
      confirmPasswordPlaceholder: 'Confirmez votre mot de passe',
      passwordsDoNotMatch: 'Les mots de passe ne correspondent pas',
      enterCode: 'Entrez le code de vérification',
      or: 'ou',
      sendCode: 'Envoyer le code',
      verify: 'Vérifier',
      success: 'Succès !',
      loginSuccess: 'Connexion réussie',
      registerSuccess: 'Inscription réussie',
      agreeTerms: "J’accepte les Conditions d’utilisation et la Politique de confidentialité",
      termsAndPrivacy: 'En continuant, vous acceptez nos',
      terms: 'Conditions d’utilisation',
      and: 'et',
      privacy: 'Politique de confidentialité',
      sending: 'Envoi...'
    },
    footer: {
      about: 'À Propos',
      terms: 'Conditions',
      privacy: 'Confidentialité',
      support: 'Support',
      api: 'API Docs',
      fees: 'Frais',
      announcement: 'Annonces',
      careers: 'Carrières',
      copyright: '© 2024 CRYPTONX. Tous droits réservés.'
    },
    homepage: {
      cta: {
        title: 'Prêt à commencer votre\nvoyage de richesse?',
        description: 'Rejoignez-nous et contrôlez vos gains',
        button: 'Commencer à trader'
      }
    },
    common: {
      search: 'Rechercher',
      filter: 'Filtrer',
      all: 'Tout',
      confirm: 'Confirmer',
      cancel: 'Annuler',
      submit: 'Soumettre',
      save: 'Sauvegarder',
      delete: 'Supprimer',
      edit: 'Modifier',
      view: 'Voir',
      download: 'Télécharger',
      upload: 'Uploader',
      loading: 'Chargement...',
      noData: 'Aucune Donnée',
      error: 'Erreur',
      success: 'Succès',
      warning: 'Avertissement',
      info: 'Info',
      more: 'Plus',
      less: 'Moins',
      expand: 'Développer',
      collapse: 'Réduire'
    }
  },
  de: {
    nav: {
      markets: 'Märkte',
      trading: 'Handel',
      stocks: 'Aktien',
      forex: 'Forex',
      assets: 'Vermögen',
      deposit: 'Einzahlung',
      withdraw: 'Abhebung',
      login: 'Anmelden',
      register: 'Registrieren',
      logout: 'Abmelden',
      profile: 'Profil',
      language: 'Sprache'
    },
    hero: {
      title: 'Führende Kryptowährungsbörse Weltweit',
      subtitle: 'Sicherer, Schneller und Professioneller Handel',
      startTrading: 'Handel Starten',
      learnMore: 'Mehr Erfahren',
      trustUsers: 'Vertrauende Nutzer',
      dailyVolume: '24h Volumen',
      countries: 'Länder',
      coins: 'Gelistete Coins'
    },
    features: {
      title: 'Warum Uns Wählen',
      security: 'Banksicherheit',
      securityDesc: 'Kalt-/Warmwallet-Trennung, Multi-Signatur',
      speed: 'Blitzschnell',
      speedDesc: 'Matching-Engine 1M Trades/Sek',
      lowFee: 'Niedrige Gebühren',
      lowFeeDesc: 'Maker 0.08%, Taker 0.1%, VIP noch besser',
      global: 'Globaler Service',
      globalDesc: '100+ Länder, 24/7 Support'
    },
    market: {
      title: 'Beliebte Paare',
      pair: 'Paar',
      price: 'Letzter Preis',
      change: '24h Änderung',
      volume: '24h Volumen',
      high: '24h Hoch',
      low: '24h Tief',
      action: 'Handeln'
    },
    marketTrends: {
      title: 'Markttrends',
      viewMore: 'Mehr anzeigen',
      categories: {
        forex: 'Forex',
        stocks: 'Aktien',
        crypto: 'Kryptowährungen',
        futures: 'Futures',
        metals: 'Edelmetalle'
      },
      table: {
        pair: 'Paar',
        price: 'Letzter Preis',
        change: '24h Änderung',
        high: '24h Hoch',
        volume: '24h Volumen',
        trend: 'Trend'
      }
    },
    trading: {
      buy: 'Kaufen',
      sell: 'Verkaufen',
      limit: 'Limit',
      market: 'Markt',
      stop: 'Stop',
      amount: 'Menge',
      price: 'Preis',
      total: 'Gesamt',
      available: 'Verfügbar',
      orderBook: 'Orderbuch',
      recentTrades: 'Letzte Trades',
      myOrders: 'Meine Orders',
      placeOrder: 'Order Platzieren',
      cancel: 'Abbrechen',
      filled: 'Erfüllt',
      pending: 'Ausstehend',
      cancelled: 'Abgebrochen'
    },
    assets: {
      title: 'Meine Vermögen',
      totalAssets: 'Gesamtvermögen',
      available: 'Verfügbar',
      frozen: 'Eingefroren',
      coin: 'Coin',
      balance: 'Guthaben',
      value: 'Wert',
      deposit: 'Einzahlung',
      withdraw: 'Abhebung',
      transfer: 'Übertragen',
      history: 'Verlauf'
    },
    auth: {
      login: 'Anmelden',
      register: 'Registrieren',
      email: 'E-Mail',
      password: 'Passwort',
      confirmPassword: 'Passwort Bestätigen',
      forgotPassword: 'Passwort Vergessen?',
      noAccount: 'Kein Konto?',
      hasAccount: 'Bereits ein Konto?',
      loginNow: 'Jetzt Anmelden',
      registerNow: 'Jetzt Registrieren',
      googleLogin: 'Mit Google Anmelden',
      signInWithGoogle: 'Mit Google Anmelden',
      createAccount: 'Konto Erstellen',
      startTrading: 'Starten Sie Ihre Trading-Reise',
      signInSubtitle: 'Melden Sie sich mit Ihrer E-Mail an, um fortzufahren',
      signUpSubtitle: 'Registrieren Sie sich, um zu beginnen',
      welcome: 'Willkommen',
      welcomeBack: 'Willkommen zurück',
      accessAccount: 'Greifen Sie auf Ihr Konto zu und setzen Sie Ihre Reise mit uns fort',
      emailAddress: 'E-Mail-Adresse',
      keepMeSignedIn: 'Angemeldet bleiben',
      resetPassword: 'Passwort zurücksetzen',
      signIn: 'Anmelden',
      signInLoading: 'Anmeldung läuft...',
      signUp: 'Registrieren',
      signUpLoading: 'Registrierung läuft...',
      createAccountLoading: 'Konto wird erstellt...',
      orContinueWith: 'Oder fortfahren mit',
      newToPlatform: 'Neu auf unserer Plattform?',
      alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
      enterEmail: 'Geben Sie Ihre E-Mail ein',
      enterPhone: 'Geben Sie Ihre Telefonnummer ein (optional)',
      enterPassword: 'Geben Sie Ihr Passwort ein',
      enterEmailPlaceholder: 'Geben Sie Ihre E-Mail-Adresse ein',
      enterPasswordPlaceholder: 'Geben Sie Ihr Passwort ein',
      createPasswordPlaceholder: 'Passwort erstellen (min. 6 Zeichen)',
      confirmPasswordPlaceholder: 'Bestätigen Sie Ihr Passwort',
      passwordsDoNotMatch: 'Die Passwörter stimmen nicht überein',
      enterCode: 'Bestätigungscode eingeben',
      or: 'oder',
      sendCode: 'Code senden',
      verify: 'Bestätigen',
      success: 'Erfolg!',
      loginSuccess: 'Login erfolgreich',
      registerSuccess: 'Registrierung erfolgreich',
      agreeTerms: 'Ich stimme den Nutzungsbedingungen und der Datenschutzerklärung zu',
      termsAndPrivacy: 'Durch Fortfahren stimmen Sie unseren zu',
      terms: 'Nutzungsbedingungen',
      and: 'und',
      privacy: 'Datenschutzerklärung',
      sending: 'Senden...',
      codeSentTitle: 'Prüfen Sie Ihr Postfach',
      codeSentSubtitle: 'Wir haben Ihnen einen Code gesendet',
      resendCode: 'Code erneut senden',
      back: 'Zurück',
      continue: 'Weiter',
      continueToDashboard: 'Zum Dashboard',
      termsNoticeLogin: 'Mit dem Login stimmen Sie den folgenden Dokumenten zu',
      msa: 'MSA',
      productTerms: 'Produktbedingungen',
      policies: 'Richtlinien',
      privacyNotice: 'Datenschutzhinweis',
      cookieNotice: 'Cookie-Hinweis'
    },
    footer: {
      about: 'Über Uns',
      terms: 'Nutzungsbedingungen',
      privacy: 'Datenschutz',
      support: 'Support',
      api: 'API Docs',
      fees: 'Gebühren',
      announcement: 'Ankündigungen',
      careers: 'Karriere',
      copyright: '© 2024 CRYPTONX. Alle Rechte vorbehalten.'
    },
    homepage: {
      cta: {
        title: 'Bereit, um Ihre\nReichtumsjourney zu beginnen?',
        description: 'Melden Sie sich an und kontrollieren Sie Ihre Gewinne',
        button: 'Handel beginnen'
      }
    },
    common: {
      search: 'Suchen',
      filter: 'Filter',
      all: 'Alle',
      confirm: 'Bestätigen',
      cancel: 'Abbrechen',
      submit: 'Senden',
      save: 'Speichern',
      delete: 'Löschen',
      edit: 'Bearbeiten',
      view: 'Ansehen',
      download: 'Herunterladen',
      upload: 'Hochladen',
      loading: 'Laden...',
      noData: 'Keine Daten',
      error: 'Fehler',
      success: 'Erfolg',
      warning: 'Warnung',
      info: 'Info',
      more: 'Mehr',
      less: 'Weniger',
      expand: 'Erweitern',
      collapse: 'Zusammenklappen'
    }
  },
  ru: {
    nav: {
      markets: 'Рынки',
      trading: 'Торговля',
      stocks: 'Акции',
      forex: 'Форекс',
      assets: 'Активы',
      deposit: 'Депозит',
      withdraw: 'Вывод',
      login: 'Войти',
      register: 'Регистрация',
      logout: 'Выйти',
      profile: 'Профиль',
      language: 'Язык'
    },
    hero: {
      title: 'Ведущая Криптовалютная Биржа',
      subtitle: 'Безопасная, Быстрая и Профессиональная Торговля',
      startTrading: 'Начать Торговать',
      learnMore: 'Узнать Больше',
      trustUsers: 'Доверенных Пользователей',
      dailyVolume: 'Объем 24ч',
      countries: 'Стран',
      coins: 'Монет'
    },
    features: {
      title: 'Почему Мы',
      security: 'Банковская Безопасность',
      securityDesc: 'Разделение кошельков, мультиподпись',
      speed: 'Сверхбыстро',
      speedDesc: 'Движок 1М сделок/сек',
      lowFee: 'Низкие Комиссии',
      lowFeeDesc: 'Мейкер 0.08%, Тейкер 0.1%',
      global: 'Глобальный Сервис',
      globalDesc: '100+ стран, поддержка 24/7'
    },
    market: {
      title: 'Популярные Пары',
      pair: 'Пара',
      price: 'Цена',
      change: 'Изменение 24ч',
      volume: 'Объем 24ч',
      high: 'Макс 24ч',
      low: 'Мин 24ч',
      action: 'Торговать'
    },
    marketTrends: {
      title: 'Тренды рынка',
      viewMore: 'Показать больше',
      categories: {
        forex: 'Форекс',
        stocks: 'Акции',
        crypto: 'Криптовалюты',
        futures: 'Фьючерсы',
        metals: 'Драгоценные металлы'
      },
      table: {
        pair: 'Пара',
        price: 'Цена',
        change: 'Изменение 24ч',
        high: 'Макс 24ч',
        volume: 'Объем 24ч',
        trend: 'Тренд'
      }
    },
    trading: {
      buy: 'Купить',
      sell: 'Продать',
      limit: 'Лимит',
      market: 'Рынок',
      stop: 'Стоп',
      amount: 'Количество',
      price: 'Цена',
      total: 'Итого',
      available: 'Доступно',
      orderBook: 'Стакан',
      recentTrades: 'Сделки',
      myOrders: 'Мои Ордера',
      placeOrder: 'Разместить',
      cancel: 'Отменить',
      filled: 'Исполнен',
      pending: 'Ожидание',
      cancelled: 'Отменен'
    },
    assets: {
      title: 'Мои Активы',
      totalAssets: 'Всего',
      available: 'Доступно',
      frozen: 'Заморожено',
      coin: 'Монета',
      balance: 'Баланс',
      value: 'Стоимость',
      deposit: 'Депозит',
      withdraw: 'Вывод',
      transfer: 'Перевод',
      history: 'История'
    },
    auth: {
      login: 'Войти',
      register: 'Регистрация',
      email: 'Email',
      password: 'Пароль',
      confirmPassword: 'Подтвердите Пароль',
      forgotPassword: 'Забыли Пароль?',
      noAccount: 'Нет Аккаунта?',
      hasAccount: 'Есть Аккаунт?',
      loginNow: 'Войти',
      registerNow: 'Зарегистрироваться',
      googleLogin: 'Войти через Google',
      signInWithGoogle: 'Войти через Google',
      createAccount: 'Создать Аккаунт',
      startTrading: 'Начните свой путь в трейдинге',
      signInSubtitle: 'Введите e-mail, чтобы продолжить',
      signUpSubtitle: 'Зарегистрируйтесь, чтобы начать',
      welcome: 'Добро пожаловать',
      welcomeBack: 'С возвращением',
      accessAccount: 'Получите доступ к своей учетной записи и продолжите путешествие с нами',
      emailAddress: 'Адрес электронной почты',
      keepMeSignedIn: 'Оставаться в системе',
      resetPassword: 'Сбросить пароль',
      signIn: 'Войти',
      signInLoading: 'Вход в систему...',
      signUp: 'Регистрация',
      signUpLoading: 'Регистрация...',
      createAccountLoading: 'Создание аккаунта...',
      orContinueWith: 'Или продолжить с',
      newToPlatform: 'Впервые на нашей платформе?',
      alreadyHaveAccount: 'Уже есть аккаунт?',
      enterEmail: 'Введите ваш e-mail',
      enterPhone: 'Введите номер телефона (необязательно)',
      enterPassword: 'Введите ваш пароль',
      enterEmailPlaceholder: 'Введите ваш адрес электронной почты',
      enterPasswordPlaceholder: 'Введите ваш пароль',
      createPasswordPlaceholder: 'Создайте пароль (мин. 6 символов)',
      confirmPasswordPlaceholder: 'Подтвердите ваш пароль',
      passwordsDoNotMatch: 'Пароли не совпадают',
      enterCode: 'Введите код подтверждения',
      or: 'или',
      sendCode: 'Отправить код',
      verify: 'Подтвердить',
      success: 'Успешно!',
      loginSuccess: 'Вход Выполнен',
      registerSuccess: 'Регистрация Успешна',
      agreeTerms: 'Я соглашаюсь с Условиями использования и Политикой конфиденциальности',
      termsAndPrivacy: 'Продолжая, вы принимаете наши',
      terms: 'Условия использования',
      and: 'и',
      privacy: 'Политику конфиденциальности',
      sending: 'Отправка...',
      codeSentTitle: 'Проверьте почту',
      codeSentSubtitle: 'Мы отправили код подтверждения',
      resendCode: 'Отправить код повторно',
      back: 'Назад',
      continue: 'Продолжить',
      continueToDashboard: 'Перейти в кабинет',
      termsNoticeLogin: 'Входя в систему, вы соглашаетесь со следующими документами',
      msa: 'MSA',
      productTerms: 'Условия продукта',
      policies: 'Политики',
      privacyNotice: 'Уведомление о конфиденциальности',
      cookieNotice: 'Уведомление о cookie'
    },
    footer: {
      about: 'О Нас',
      terms: 'Условия',
      privacy: 'Конфиденциальность',
      support: 'Поддержка',
      api: 'API Документы',
      fees: 'Комиссии',
      announcement: 'Объявления',
      careers: 'Карьера',
      copyright: '© 2024 CRYPTONX. Все права защищены.'
    },
    homepage: {
      cta: {
        title: 'Готовы начать свой\nпутешествие к богатству?',
        description: 'Присоединяйтесь к нам и контролируйте свои доходы',
        button: 'Начать торговлю'
      }
    },
    common: {
      search: 'Поиск',
      filter: 'Фильтр',
      all: 'Все',
      confirm: 'Подтвердить',
      cancel: 'Отмена',
      submit: 'Отправить',
      save: 'Сохранить',
      delete: 'Удалить',
      edit: 'Изменить',
      view: 'Просмотр',
      download: 'Скачать',
      upload: 'Загрузить',
      loading: 'Загрузка...',
      noData: 'Нет Данных',
      error: 'Ошибка',
      success: 'Успех',
      warning: 'Внимание',
      info: 'Инфо',
      more: 'Еще',
      less: 'Меньше',
      expand: 'Развернуть',
      collapse: 'Свернуть'
    }
  }
};